// Layer 3 — pure deterministic library. Allowed imports: '../types' only.
// No React, no framer-motion, no '@tauri-apps/*' direct.
//
// Detect-only image deduplication. claude.md Behavioral Rule #2 forbids
// touching the source image folders, so this module *never* deletes — it
// only reports clusters of likely duplicates so the designer can decide
// manually (e.g. open Explorer and reorganise outside the app).
//
// Two-pass algorithm:
//
//   Pass 1 (cheap, sync) — bucket by `${sizeBytes}|${normalizedName}`. The
//     normalisation strips Windows / Hebrew copy suffixes ("(1)", " - copy",
//     " - העתק", …) so that "שולחן.jpg" and "שולחן (1).jpg" collapse to the
//     same key.
//
//   Pass 2 (perceptual) — compute a 64-bit dHash on every image's cached
//     thumbnail. Two hashes are considered the same image iff the Hamming
//     distance ≤ 5. To avoid the O(n²) blow-up on the full library (~880
//     images), we bucket by the leading 16 bits and only compare within
//     buckets — neighbouring 16-bit prefixes are also probed because a
//     single bit-flip near the boundary would otherwise split a true match.
//
// The two passes are then merged: pairs flagged by both → reason 'name+hash',
// only Pass 1 → 'name', only Pass 2 → 'hash'. Each cluster's "canonical"
// image is the one with the smallest `modifiedAt` (the original capture).

import { type ImageMetadata } from '../types';

// ===========================================================================
// Public surface
// ===========================================================================

export type DuplicateReason = 'name' | 'hash' | 'name+hash';

export type DuplicateCluster = {
  /** The earliest-modified image in the cluster (treated as the original). */
  canonical: ImageMetadata;
  /** All other images in the cluster, sorted by modifiedAt ascending. */
  duplicates: ImageMetadata[];
  /** Which pass(es) flagged the cluster. */
  reason: DuplicateReason;
};

export type FindDuplicatesOptions = {
  /** Allow the caller to abort an in-flight scan (UI close button). */
  signal?: AbortSignal;
  /** Fired after every processed image so the UI can update its progress bar. */
  onProgress?: (done: number, total: number) => void;
  /**
   * Hamming-distance threshold for the perceptual hash. Defaults to 5 — a
   * value chosen empirically: < 4 misses near-identical re-encodes, > 6
   * starts to glue together unrelated white-on-white napkin shots.
   */
  hashThreshold?: number;
};

const DEFAULT_HASH_THRESHOLD = 5 as const;

// ===========================================================================
// Filename normalization (Pass 1)
// ===========================================================================

/**
 * Strip common Windows / Hebrew copy markers from a filename so siblings
 * generated by File Explorer's "Copy and paste" collapse to the same bucket.
 *
 * Lowercase + NFC so Hebrew composition does not split equivalent code-point
 * sequences across buckets.
 *
 * Exported for the unit test only.
 */
export function normalizeName(name: string): string {
  let n = (name ?? '').normalize('NFC').toLowerCase();
  // Drop trailing extension if present so "foo (1).jpg" and "foo.jpg" land
  // in the same bucket (the size match is what discriminates pixel-level
  // identity later — file size includes the extension's bytes anyway).
  const dot = n.lastIndexOf('.');
  if (dot > 0 && dot >= n.length - 5) {
    n = n.slice(0, dot);
  }
  // Remove " (1)", " (12)", "(2)" trailing segments — possibly repeated.
  n = n.replace(/\s*\(\d+\)\s*$/g, '');
  // Remove " - copy", " - copy (2)", " - העתק", " - עותק", "- עותק (3)".
  n = n.replace(/\s*-\s*(copy|העתק|עותק)(\s*\(\d+\))?\s*$/gi, '');
  // Collapse double whitespace and trim.
  n = n.replace(/\s+/g, ' ').trim();
  return n;
}

// ===========================================================================
// Perceptual hash (Pass 2 — dHash 8x8)
// ===========================================================================

/** 64 bits = 8 bytes — one Uint8Array entry per row of the 9x8 grid. */
const DHASH_BYTES = 8 as const;
const DHASH_W = 9 as const;
const DHASH_H = 8 as const;

type Canvas2D = {
  width: number;
  height: number;
  getContext(id: '2d'): CanvasRenderingContext2D | null;
};

function isOffscreenCanvasAvailable(): boolean {
  return (
    typeof globalThis !== 'undefined' &&
    typeof (globalThis as unknown as { OffscreenCanvas?: unknown })
      .OffscreenCanvas !== 'undefined'
  );
}

function makeCanvas(width: number, height: number): Canvas2D | null {
  if (isOffscreenCanvasAvailable()) {
    try {
      return new (
        globalThis as unknown as {
          OffscreenCanvas: new (w: number, h: number) => Canvas2D;
        }
      ).OffscreenCanvas(width, height);
    } catch {
      // Fall through to the DOM canvas — some Workers refuse OffscreenCanvas.
    }
  }
  if (typeof document === 'undefined') return null;
  const c = document.createElement('canvas');
  c.width = width;
  c.height = height;
  return c as unknown as Canvas2D;
}

/**
 * Compute the 8x8 difference hash of a thumbnail blob. Returns null on any
 * decode / canvas failure so the caller can skip the image without aborting.
 *
 * Algorithm:
 *   1. Decode → 9x8 greyscale (luma = 0.299R + 0.587G + 0.114B).
 *   2. For each row: emit 8 bits comparing pixel[x] > pixel[x+1].
 *   3. Pack into an 8-byte Uint8Array, MSB-first per row.
 *
 * Exported for the unit test only.
 */
export async function computeDHash(blob: Blob): Promise<Uint8Array | null> {
  if (!blob || typeof (blob as Blob).size !== 'number') return null;
  if (typeof createImageBitmap !== 'function') return null;

  let bitmap: ImageBitmap;
  try {
    bitmap = await createImageBitmap(blob);
  } catch {
    return null;
  }

  const canvas = makeCanvas(DHASH_W, DHASH_H);
  if (!canvas) {
    bitmap.close?.();
    return null;
  }
  const ctx = canvas.getContext('2d');
  if (!ctx) {
    bitmap.close?.();
    return null;
  }

  try {
    ctx.drawImage(bitmap as unknown as CanvasImageSource, 0, 0, DHASH_W, DHASH_H);
  } catch {
    bitmap.close?.();
    return null;
  }
  bitmap.close?.();

  let data: ImageData;
  try {
    data = ctx.getImageData(0, 0, DHASH_W, DHASH_H);
  } catch {
    return null;
  }
  const px = data.data;

  // Build a 9x8 luma grid first (row-major) so the row-wise compare is clean.
  const luma = new Float32Array(DHASH_W * DHASH_H);
  for (let i = 0; i < luma.length; i += 1) {
    const r = px[i * 4] ?? 0;
    const g = px[i * 4 + 1] ?? 0;
    const b = px[i * 4 + 2] ?? 0;
    luma[i] = 0.299 * r + 0.587 * g + 0.114 * b;
  }

  const out = new Uint8Array(DHASH_BYTES);
  for (let y = 0; y < DHASH_H; y += 1) {
    let rowBits = 0;
    for (let x = 0; x < DHASH_H; x += 1) {
      const left = luma[y * DHASH_W + x] ?? 0;
      const right = luma[y * DHASH_W + x + 1] ?? 0;
      // MSB at bit 7 → consistent with how we'll iterate later.
      if (left > right) {
        rowBits |= 1 << (7 - x);
      }
    }
    out[y] = rowBits;
  }
  return out;
}

/**
 * Hamming distance between two 64-bit hashes (8-byte Uint8Arrays).
 * Returns Number.POSITIVE_INFINITY if either argument is missing so the
 * comparison naturally fails.
 */
export function hammingDistance(
  a: Uint8Array | null | undefined,
  b: Uint8Array | null | undefined,
): number {
  if (!a || !b || a.length !== DHASH_BYTES || b.length !== DHASH_BYTES) {
    return Number.POSITIVE_INFINITY;
  }
  let d = 0;
  for (let i = 0; i < DHASH_BYTES; i += 1) {
    let v = (a[i] ?? 0) ^ (b[i] ?? 0);
    // Brian Kernighan popcount.
    while (v !== 0) {
      v &= v - 1;
      d += 1;
    }
  }
  return d;
}

// ===========================================================================
// Union–Find (small, dependency-free)
// ===========================================================================

class DSU {
  private parent: number[];
  private rank: number[];
  constructor(size: number) {
    this.parent = new Array<number>(size);
    this.rank = new Array<number>(size).fill(0);
    for (let i = 0; i < size; i += 1) this.parent[i] = i;
  }
  find(x: number): number {
    let r = x;
    while (this.parent[r] !== r) r = this.parent[r] as number;
    // Path-compress.
    let cur = x;
    while (this.parent[cur] !== r) {
      const next = this.parent[cur] as number;
      this.parent[cur] = r;
      cur = next;
    }
    return r;
  }
  union(a: number, b: number): void {
    const ra = this.find(a);
    const rb = this.find(b);
    if (ra === rb) return;
    const rkA = this.rank[ra] ?? 0;
    const rkB = this.rank[rb] ?? 0;
    if (rkA < rkB) {
      this.parent[ra] = rb;
    } else if (rkA > rkB) {
      this.parent[rb] = ra;
    } else {
      this.parent[rb] = ra;
      this.rank[ra] = rkA + 1;
    }
  }
  /** Group all indices by their root. */
  groups(): Map<number, number[]> {
    const out = new Map<number, number[]>();
    for (let i = 0; i < this.parent.length; i += 1) {
      const root = this.find(i);
      const bucket = out.get(root);
      if (bucket) bucket.push(i);
      else out.set(root, [i]);
    }
    return out;
  }
}

// ===========================================================================
// Public driver
// ===========================================================================

const O_N2_FALLBACK_LIMIT = 1000 as const;
const HASH_BUCKET_BITS = 16 as const;

function bucketKeyFor(hash: Uint8Array): number {
  // First two bytes interpreted as a 16-bit unsigned int.
  return ((hash[0] ?? 0) << 8) | (hash[1] ?? 0);
}

/**
 * Detect-only deduplicator. Walks the library and returns clusters of
 * likely-identical images. Never mutates the file system.
 *
 * Failures (thumbnail decode, AbortSignal, …) downgrade gracefully — the
 * faulty image is dropped from Pass 2 but still participates in Pass 1.
 */
export async function findDuplicates(
  images: readonly ImageMetadata[],
  getThumbBlob: (image: ImageMetadata) => Promise<Blob | null>,
  opts: FindDuplicatesOptions = {},
): Promise<DuplicateCluster[]> {
  const { signal, onProgress } = opts;
  const threshold = Math.max(0, Math.floor(opts.hashThreshold ?? DEFAULT_HASH_THRESHOLD));

  const total = images.length;
  if (total === 0) return [];

  // -----------------------------------------------------------------------
  // Pass 1 — name + size buckets.
  // -----------------------------------------------------------------------
  const nameBuckets = new Map<string, number[]>();
  for (let i = 0; i < total; i += 1) {
    const img = images[i]!;
    const key = `${img.sizeBytes}|${normalizeName(img.name)}`;
    const list = nameBuckets.get(key);
    if (list) list.push(i);
    else nameBuckets.set(key, [i]);
  }

  const dsu = new DSU(total);
  const flaggedByName = new Set<string>(); // "minIdx|maxIdx" pairs

  for (const indices of nameBuckets.values()) {
    if (indices.length < 2) continue;
    // Union all members of the bucket — they share the same normalized name
    // AND the same size, so we treat the whole group as one cluster.
    const a = indices[0]!;
    for (let k = 1; k < indices.length; k += 1) {
      const b = indices[k]!;
      dsu.union(a, b);
      const lo = Math.min(a, b);
      const hi = Math.max(a, b);
      flaggedByName.add(`${lo}|${hi}`);
    }
    // Every internal pair counts as "name-flagged" for the merge step.
    for (let p = 0; p < indices.length; p += 1) {
      for (let q = p + 1; q < indices.length; q += 1) {
        const lo = Math.min(indices[p]!, indices[q]!);
        const hi = Math.max(indices[p]!, indices[q]!);
        flaggedByName.add(`${lo}|${hi}`);
      }
    }
  }

  // -----------------------------------------------------------------------
  // Pass 2 — perceptual hash.
  // -----------------------------------------------------------------------
  const hashes: Array<Uint8Array | null> = new Array(total).fill(null);
  let processed = 0;

  // Bake hashes serially so the thumbnail bake queue inside `images.ts`
  // (concurrency 4) is the actual rate limiter — we don't want to fan out
  // 880 thumbnail decodes in parallel here.
  for (let i = 0; i < total; i += 1) {
    if (signal?.aborted) break;
    const img = images[i]!;
    if (img.kind === 'image') {
      try {
        const blob = await getThumbBlob(img);
        if (blob) {
          hashes[i] = await computeDHash(blob);
        }
      } catch (cause) {
        // Per-image failure is non-fatal — log and continue.
        // eslint-disable-next-line no-console
        console.error('[dedup] hash failed for', img.path, cause);
      }
    }
    processed += 1;
    if (onProgress) {
      try {
        onProgress(processed, total);
      } catch {
        /* never let a callback abort the scan */
      }
    }
  }

  if (signal?.aborted) {
    // The caller will discard the partial result — return what we have so a
    // re-scan starts from a clean slate.
    return [];
  }

  // Flag pairs by hash. Bucketing for n > 1000, naive O(n²) below that.
  const flaggedByHash = new Set<string>();
  const flagPair = (a: number, b: number): void => {
    if (a === b) return;
    const lo = Math.min(a, b);
    const hi = Math.max(a, b);
    flaggedByHash.add(`${lo}|${hi}`);
    dsu.union(lo, hi);
  };

  if (total <= O_N2_FALLBACK_LIMIT) {
    for (let i = 0; i < total; i += 1) {
      const hi = hashes[i];
      if (!hi) continue;
      for (let j = i + 1; j < total; j += 1) {
        const hj = hashes[j];
        if (!hj) continue;
        if (hammingDistance(hi, hj) <= threshold) {
          flagPair(i, j);
        }
      }
    }
  } else {
    // Bucket by 16-bit prefix of the hash. To survive a bit-flip near the
    // boundary, also probe each bucket's neighbours at distance ≤ 1 in
    // 1-bit-flip sense (i.e. all 16 single-bit flips of the prefix).
    const buckets = new Map<number, number[]>();
    for (let i = 0; i < total; i += 1) {
      const h = hashes[i];
      if (!h) continue;
      const key = bucketKeyFor(h);
      const list = buckets.get(key);
      if (list) list.push(i);
      else buckets.set(key, [i]);
    }

    const probeKeys = (key: number): number[] => {
      // Self + every 1-bit flip of the prefix.
      const out: number[] = [key];
      for (let b = 0; b < HASH_BUCKET_BITS; b += 1) {
        out.push(key ^ (1 << b));
      }
      return out;
    };

    const seenBucketPair = new Set<string>();
    for (const [key, indices] of buckets) {
      // Pairs *inside* a single bucket.
      for (let p = 0; p < indices.length; p += 1) {
        for (let q = p + 1; q < indices.length; q += 1) {
          const a = indices[p]!;
          const b = indices[q]!;
          const ha = hashes[a]!;
          const hb = hashes[b]!;
          if (hammingDistance(ha, hb) <= threshold) flagPair(a, b);
        }
      }
      // Pairs *between* this bucket and its 1-flip neighbours. Avoid double
      // work by sorting the (key, neighbour) pair and storing the visited
      // edge.
      for (const nKey of probeKeys(key)) {
        if (nKey === key) continue;
        const lo = Math.min(key, nKey);
        const hi = Math.max(key, nKey);
        const edgeId = `${lo}-${hi}`;
        if (seenBucketPair.has(edgeId)) continue;
        seenBucketPair.add(edgeId);
        const neighbour = buckets.get(nKey);
        if (!neighbour) continue;
        for (const a of indices) {
          const ha = hashes[a]!;
          for (const b of neighbour) {
            const hb = hashes[b]!;
            if (hammingDistance(ha, hb) <= threshold) flagPair(a, b);
          }
        }
      }
    }
  }

  // -----------------------------------------------------------------------
  // Merge — build clusters from the union-find groups, decide the reason.
  // -----------------------------------------------------------------------
  const groups = dsu.groups();
  const clusters: DuplicateCluster[] = [];

  for (const indices of groups.values()) {
    if (indices.length < 2) continue;

    // Sort by modifiedAt ascending so the canonical (oldest) is first. Tie-
    // break on path so the order is deterministic for tests.
    const sorted = indices
      .map((idx) => ({ idx, img: images[idx]! }))
      .sort((a, b) => {
        if (a.img.modifiedAt !== b.img.modifiedAt) {
          return a.img.modifiedAt - b.img.modifiedAt;
        }
        return a.img.path.localeCompare(b.img.path, 'he');
      });

    // Determine the reason: scan all internal pairs and merge their flags.
    let sawName = false;
    let sawHash = false;
    for (let p = 0; p < sorted.length; p += 1) {
      for (let q = p + 1; q < sorted.length; q += 1) {
        const lo = Math.min(sorted[p]!.idx, sorted[q]!.idx);
        const hi = Math.max(sorted[p]!.idx, sorted[q]!.idx);
        const id = `${lo}|${hi}`;
        if (flaggedByName.has(id)) sawName = true;
        if (flaggedByHash.has(id)) sawHash = true;
        if (sawName && sawHash) break;
      }
      if (sawName && sawHash) break;
    }

    let reason: DuplicateReason;
    if (sawName && sawHash) reason = 'name+hash';
    else if (sawName) reason = 'name';
    else if (sawHash) reason = 'hash';
    else continue; // shouldn't happen — DSU only unions on a flag

    clusters.push({
      canonical: sorted[0]!.img,
      duplicates: sorted.slice(1).map((s) => s.img),
      reason,
    });
  }

  // Stable cluster order — by canonical path.
  clusters.sort((a, b) =>
    a.canonical.path.localeCompare(b.canonical.path, 'he'),
  );
  return clusters;
}
